#[test_only]
module orcus::orcus_tests;

use sui::test_scenario::{Self as ts, Scenario};
use sui::coin::{Self, Coin, TreasuryCap};
use sui::sui::SUI;
use sui::clock::{Self, Clock};
use orcus::vault::{Self, Vault, OwnerCap, AgentCap};
use orcus::oracle::{Self, PriceOracle};
use orcus::dex::{Self, Pool};
use orcus::orcus_usdc::{Self, ORCUS_USDC};

const OWNER: address = @0xACE;   // deployer: holds TreasuryCap, OwnerCap, AgentCap
const USER: address = @0xa11ce;  // must match the signed test vector

// ed25519 attestation test vector (generated by agent/scripts/sui-vector.ts, seed=0x07*32)
const PUBKEY: vector<u8> = x"ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c";
const SIG: vector<u8> = x"ae3044a725a414a1b90e6387444ceb6757e95462c2d86235f42c8c3d62bad7ebfba81595538ea95081c10ed70682a9ff9af239bda703dc414239129111abe20d";
const RECEIPT: vector<u8> = x"1111111111111111111111111111111111111111111111111111111111111111";
const DEADLINE: u64 = 9000000000000;
const PRICE: u128 = 500000;        // $0.5 scaled by 1e6
const AMOUNT_IN: u64 = 1000000;    // 1e6 SUI units
const EXPECTED_OUT: u64 = 500000;  // 1e6 * 0.5

fun init_all(s: &mut Scenario) {
    orcus_usdc::init_for_testing(ts::ctx(s));
    oracle::init_for_testing(ts::ctx(s));
    dex::init_for_testing(ts::ctx(s));
    vault::init_for_testing(ts::ctx(s));
}

// Bootstrap: publish, fund the pool, set attestor, USER deposits. Returns scenario
// positioned after the deposit (ready for an execute call by OWNER as agent).
fun bootstrap(): Scenario {
    let mut s = ts::begin(OWNER);
    init_all(&mut s);

    ts::next_tx(&mut s, OWNER);
    {
        let mut treasury = ts::take_from_sender<TreasuryCap<ORCUS_USDC>>(&s);
        let usdc = coin::mint(&mut treasury, 1_000_000_000, ts::ctx(&mut s));
        let mut pool = ts::take_shared<Pool>(&s);
        dex::fund(&mut pool, usdc);
        ts::return_shared(pool);
        ts::return_to_sender(&s, treasury);

        let owner_cap = ts::take_from_sender<OwnerCap>(&s);
        let mut vault = ts::take_shared<Vault>(&s);
        vault::set_attestor(&owner_cap, &mut vault, PUBKEY);
        ts::return_shared(vault);
        ts::return_to_sender(&s, owner_cap);
    };

    ts::next_tx(&mut s, USER);
    {
        let mut vault = ts::take_shared<Vault>(&s);
        let payment = coin::mint_for_testing<SUI>(AMOUNT_IN, ts::ctx(&mut s));
        vault::deposit(&mut vault, payment, b"ciphertext", 100, ts::ctx(&mut s));
        ts::return_shared(vault);
    };

    s
}

fun do_execute(s: &mut Scenario, price: u128, agent_min_out: u64, nonce: u64, sig: vector<u8>) {
    let agent_cap = ts::take_from_sender<AgentCap>(s);
    let mut vault = ts::take_shared<Vault>(s);
    let mut pool = ts::take_shared<Pool>(s);
    let mut oracle_obj = ts::take_shared<PriceOracle>(s);
    let clock = clock::create_for_testing(ts::ctx(s));
    vault::execute_trade(
        &agent_cap, &mut vault, &mut pool, &mut oracle_obj, &clock,
        USER, price, agent_min_out, DEADLINE, RECEIPT, nonce, sig, ts::ctx(s),
    );
    clock::destroy_for_testing(clock);
    ts::return_shared(vault);
    ts::return_shared(pool);
    ts::return_shared(oracle_obj);
    ts::return_to_sender(s, agent_cap);
}

// --- message vector cross-check (proves the agent's BCS matches Move) ---

#[test]
fun exec_message_matches_vector() {
    let m = vault::exec_message_for_testing(USER, 0, DEADLINE, RECEIPT, 0);
    assert!(m == x"00000000000000000000000000000000000000000000000000000000000a11ce00000000000000000090cd792f0800002011111111111111111111111111111111111111111111111111111111111111110000000000000000", 0);
}

// --- oracle ---

#[test]
fun oracle_expected_out() {
    let mut s = ts::begin(OWNER);
    oracle::init_for_testing(ts::ctx(&mut s));
    ts::next_tx(&mut s, OWNER);
    {
        let mut o = ts::take_shared<PriceOracle>(&s);
        let clock = clock::create_for_testing(ts::ctx(&mut s));
        oracle::update_for_testing(&mut o, PRICE, &clock);
        assert!(oracle::expected_out(&o, AMOUNT_IN, &clock) == EXPECTED_OUT, 0);
        clock::destroy_for_testing(clock);
        ts::return_shared(o);
    };
    ts::end(s);
}

#[test]
#[expected_failure(abort_code = 0, location = orcus::oracle)]
fun oracle_reverts_without_price() {
    let mut s = ts::begin(OWNER);
    oracle::init_for_testing(ts::ctx(&mut s));
    ts::next_tx(&mut s, OWNER);
    {
        let o = ts::take_shared<PriceOracle>(&s);
        let clock = clock::create_for_testing(ts::ctx(&mut s));
        let _ = oracle::expected_out(&o, AMOUNT_IN, &clock);
        clock::destroy_for_testing(clock);
        ts::return_shared(o);
    };
    ts::end(s);
}

// --- vault deposit / withdraw ---

#[test]
fun deposit_then_withdraw() {
    let mut s = bootstrap();
    ts::next_tx(&mut s, USER);
    {
        let mut vault = ts::take_shared<Vault>(&s);
        assert!(vault::has_intent(&vault, USER), 0);
        vault::withdraw(&mut vault, ts::ctx(&mut s));
        assert!(!vault::has_intent(&vault, USER), 1);
        ts::return_shared(vault);
    };
    ts::next_tx(&mut s, USER);
    {
        let refund = ts::take_from_sender<Coin<SUI>>(&s);
        assert!(coin::value(&refund) == AMOUNT_IN, 2);
        coin::burn_for_testing(refund);
    };
    ts::end(s);
}

#[test]
#[expected_failure(abort_code = 1, location = orcus::vault)]
fun deposit_rejects_slippage_over_max() {
    let mut s = ts::begin(OWNER);
    init_all(&mut s);
    ts::next_tx(&mut s, USER);
    {
        let mut vault = ts::take_shared<Vault>(&s);
        let payment = coin::mint_for_testing<SUI>(AMOUNT_IN, ts::ctx(&mut s));
        vault::deposit(&mut vault, payment, b"c", 10001, ts::ctx(&mut s));
        ts::return_shared(vault);
    };
    ts::end(s);
}

// --- execution (happy path + C-01: output to USER, never the agent) ---

#[test]
fun execute_pays_user() {
    let mut s = bootstrap();
    ts::next_tx(&mut s, OWNER);
    do_execute(&mut s, PRICE, 0, 0, SIG);

    // USER receives the oUSDC output
    ts::next_tx(&mut s, USER);
    {
        let out = ts::take_from_sender<Coin<ORCUS_USDC>>(&s);
        assert!(coin::value(&out) == EXPECTED_OUT, 0);
        coin::burn_for_testing(out);
    };
    // intent cleared, nonce bumped
    ts::next_tx(&mut s, USER);
    {
        let vault = ts::take_shared<Vault>(&s);
        assert!(!vault::has_intent(&vault, USER), 1);
        assert!(vault::nonce_of(&vault, USER) == 1, 2);
        ts::return_shared(vault);
    };
    ts::end(s);
}

#[test]
#[expected_failure(abort_code = 6, location = orcus::vault)]
fun execute_rejects_bad_nonce() {
    let mut s = bootstrap();
    ts::next_tx(&mut s, OWNER);
    do_execute(&mut s, PRICE, 0, 1, SIG); // nonce 1 != expected 0
    ts::end(s);
}

#[test]
#[expected_failure(abort_code = 7, location = orcus::vault)]
fun execute_rejects_bad_attestation() {
    let mut s = bootstrap();
    ts::next_tx(&mut s, OWNER);
    let bad = x"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    do_execute(&mut s, PRICE, 0, 0, bad);
    ts::end(s);
}

#[test]
#[expected_failure(abort_code = 4, location = orcus::vault)]
fun execute_rejects_expired() {
    let mut s = bootstrap();
    ts::next_tx(&mut s, OWNER);
    {
        let agent_cap = ts::take_from_sender<AgentCap>(&s);
        let mut vault = ts::take_shared<Vault>(&s);
        let mut pool = ts::take_shared<Pool>(&s);
        let mut oracle_obj = ts::take_shared<PriceOracle>(&s);
        let mut clock = clock::create_for_testing(ts::ctx(&mut s));
        clock::set_for_testing(&mut clock, DEADLINE + 1); // past the deadline
        vault::execute_trade(
            &agent_cap, &mut vault, &mut pool, &mut oracle_obj, &clock,
            USER, PRICE, 0, DEADLINE, RECEIPT, 0, SIG, ts::ctx(&mut s),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(vault);
        ts::return_shared(pool);
        ts::return_shared(oracle_obj);
        ts::return_to_sender(&s, agent_cap);
    };
    ts::end(s);
}

#[test]
#[expected_failure(abort_code = 5, location = orcus::vault)]
fun execute_blocked_after_cancel_cooldown() {
    let mut s = bootstrap();
    // USER requests cancel
    ts::next_tx(&mut s, USER);
    {
        let mut vault = ts::take_shared<Vault>(&s);
        let clock = clock::create_for_testing(ts::ctx(&mut s)); // t=0
        vault::request_cancel(&mut vault, &clock, ts::ctx(&mut s));
        clock::destroy_for_testing(clock);
        ts::return_shared(vault);
    };
    // agent tries after the cooldown elapses -> "cancelling"
    ts::next_tx(&mut s, OWNER);
    {
        let agent_cap = ts::take_from_sender<AgentCap>(&s);
        let mut vault = ts::take_shared<Vault>(&s);
        let mut pool = ts::take_shared<Pool>(&s);
        let mut oracle_obj = ts::take_shared<PriceOracle>(&s);
        let mut clock = clock::create_for_testing(ts::ctx(&mut s));
        clock::set_for_testing(&mut clock, 3_600_001); // > CANCEL_COOLDOWN_MS
        vault::execute_trade(
            &agent_cap, &mut vault, &mut pool, &mut oracle_obj, &clock,
            USER, PRICE, 0, DEADLINE, RECEIPT, 0, SIG, ts::ctx(&mut s),
        );
        clock::destroy_for_testing(clock);
        ts::return_shared(vault);
        ts::return_shared(pool);
        ts::return_shared(oracle_obj);
        ts::return_to_sender(&s, agent_cap);
    };
    ts::end(s);
}
